-- Generated by node scripts/generate-reminder-upgrade.mjs. Do not edit by hand.
-- Paste this ENTIRE file into Supabase SQL Editor and run it as one query.
-- Requires the estate application's earlier schema migrations through
-- 202610040001_remove_joint_loans.sql. Adds only missing reminder migrations.
-- Existing settings, subscriptions, payment records and delivery history remain.
-- Safe to run again after a successful upgrade. Edge Functions deploy separately.
begin;

-- Serialize this upgrade across SQL Editor sessions.
select pg_advisory_xact_lock(20261005, 6);

do $estate_reminder_upgrade$
declare
  v_base_count integer;
  v_daily_count integer;
begin
  select count(*) into v_base_count
  from unnest(array[
    'public.advance_reminder_settings', 'public.advance_push_subscriptions',
    'public.weekly_pay_runs', 'public.advance_reminder_deliveries'
  ]) as required(name)
  where to_regclass(required.name) is not null;

  if v_base_count not in (0, 4) then
    raise exception 'The base reminder schema is incomplete. No changes were applied. Inspect migration 202610050001_advance_reminders.sql before upgrading.';
  end if;
  if v_base_count = 0 then
    if to_regclass('public.workers') is null or to_regclass('public.weekly_payments') is null
      or to_regclass('public.worker_loans') is null or to_regprocedure('public.touch_updated_at()') is null then
      raise exception 'Apply the earlier estate schema migrations before this reminder upgrade. No changes were applied.';
    end if;
    execute $reminder_1$
-- Editable advance reminders. No subscriptions or completed weeks are backfilled.
-- Run after 202610040001_remove_joint_loans.sql.

create table public.advance_reminder_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  enabled boolean not null default false,
  weekday smallint not null default 3 check (weekday between 0 and 6),
  reminder_time time(0) not null default '20:00' check (extract(second from reminder_time) = 0),
  timezone text not null default 'Asia/Kolkata' check (timezone = 'Asia/Kolkata'),
  updated_at timestamptz not null default now()
);
create trigger advance_reminder_settings_updated before update on public.advance_reminder_settings
  for each row execute function public.touch_updated_at();

create table public.advance_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique check (char_length(endpoint) between 1 and 2048),
  p256dh text not null,
  auth text not null,
  expiration_time timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_test_at timestamptz
);
create index advance_push_subscriptions_owner on public.advance_push_subscriptions (user_id);
create trigger advance_push_subscriptions_updated before update on public.advance_push_subscriptions
  for each row execute function public.touch_updated_at();

-- A marker certifies an atomic full save, including zero-pay and skipped workers.
-- The worker snapshot does not change when someone joins after the save.
create table public.weekly_pay_runs (
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null check (extract(isodow from week_start) = 3),
  completed_at timestamptz not null default now(),
  worker_ids uuid[] not null check (cardinality(worker_ids) > 0),
  primary key (user_id, week_start)
);

-- Keep delivery tombstones when a phone unsubscribes. They prevent another nag
-- for the same account, Wednesday and endpoint after subscribing again.
create table public.advance_reminder_deliveries (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  week_start date not null check (extract(isodow from week_start) = 3),
  endpoint text not null,
  subscription_id uuid references public.advance_push_subscriptions(id) on delete set null,
  scheduled_at timestamptz not null,
  status text not null default 'pending' check (status in ('pending', 'sending', 'sent', 'retry', 'uncertain', 'expired', 'cancelled')),
  attempt_count smallint not null default 0 check (attempt_count between 0 and 3),
  next_attempt_at timestamptz not null default now(),
  claimed_at timestamptz,
  sent_at timestamptz,
  last_http_status integer,
  created_at timestamptz not null default now(),
  unique (user_id, week_start, endpoint)
);
create index advance_reminder_deliveries_pending on public.advance_reminder_deliveries (status, next_attempt_at);

alter table public.advance_reminder_settings enable row level security;
alter table public.advance_push_subscriptions enable row level security;
alter table public.weekly_pay_runs enable row level security;
alter table public.advance_reminder_deliveries enable row level security;
create policy "Read own advance reminder settings" on public.advance_reminder_settings for select to authenticated using (user_id = auth.uid());
create policy "Read own advance push subscriptions" on public.advance_push_subscriptions for select to authenticated using (user_id = auth.uid());
create policy "Read own completed pay weeks" on public.weekly_pay_runs for select to authenticated using (user_id = auth.uid());
create policy "Read own advance reminder deliveries" on public.advance_reminder_deliveries for select to authenticated using (user_id = auth.uid());
revoke all on public.advance_reminder_settings, public.advance_push_subscriptions, public.weekly_pay_runs, public.advance_reminder_deliveries from public, anon, authenticated;
grant select on public.advance_reminder_settings, public.advance_push_subscriptions, public.weekly_pay_runs, public.advance_reminder_deliveries to authenticated;
grant all on public.advance_reminder_settings, public.advance_push_subscriptions, public.weekly_pay_runs, public.advance_reminder_deliveries to service_role;

-- Imports/direct record changes invalidate completion; they never manufacture
-- completion from the existence of one (or even several) imported payments.
create function public.invalidate_weekly_pay_run() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if TG_OP <> 'INSERT' then
    delete from public.weekly_pay_runs where user_id = old.user_id and week_start = old.week_start;
  end if;
  if TG_OP <> 'DELETE' then
    delete from public.weekly_pay_runs where user_id = new.user_id and week_start = new.week_start;
  end if;
  return null;
end;
$$;
revoke all on function public.invalidate_weekly_pay_run() from public;
create trigger weekly_pay_run_invalidated after insert or update or delete on public.weekly_payments
  for each row execute function public.invalidate_weekly_pay_run();

-- Explicit ownership checks are preserved. SECURITY DEFINER allows the marker
-- write without granting clients a way to mark an imported/partial week done.
create or replace function public.save_weekly_labour(p_week_start date, p_rows jsonb)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user uuid := auth.uid();
  v_row record;
  v_old public.weekly_payments%rowtype;
  v_gross numeric;
  v_rate numeric;
  v_balance numeric;
  v_worker_ids uuid[];
begin
  if v_user is null then raise exception 'Please sign in again.'; end if;
  if p_week_start is null or extract(isodow from p_week_start) <> 3 then raise exception 'Choose a Wednesday payment date.'; end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' or jsonb_array_length(p_rows) = 0 then raise exception 'No worker payments supplied.'; end if;
  if (select count(distinct row->>'worker_id') from jsonb_array_elements(p_rows) row) <> jsonb_array_length(p_rows) then raise exception 'Each worker must appear once.'; end if;
  perform id from public.workers where user_id = v_user order by id for update;
  if exists (
    select 1 from jsonb_array_elements(p_rows) row
    where not exists (select 1 from public.workers w where w.id = (row->>'worker_id')::uuid and w.user_id = v_user)
  ) then raise exception 'Worker does not belong to your account.'; end if;
  select array_agg((row->>'worker_id')::uuid order by row->>'worker_id') into v_worker_ids from jsonb_array_elements(p_rows) row;
  delete from public.worker_loans where user_id = v_user and loan_date = p_week_start and kind = 'repayment'
    and notes = 'Repayment recorded with weekly payment' and worker_id = any(v_worker_ids);
  for v_row in select * from jsonb_to_recordset(p_rows) as x(worker_id uuid, days_worked numeric, daily_rate numeric, excluded boolean, personal_deduction numeric) loop
    select * into v_old from public.weekly_payments where user_id = v_user and worker_id = v_row.worker_id and week_start = p_week_start;
    if v_row.days_worked is null or v_row.days_worked < 0 or v_row.days_worked > 7
      or ((v_row.days_worked > 6 or v_row.days_worked <> trunc(v_row.days_worked))
        and v_row.days_worked is distinct from coalesce(v_old.days_worked, round(v_old.amount / nullif(coalesce(v_old.daily_rate, v_row.daily_rate), 0), 1))) then
      raise exception 'Choose working days from 0 to 6.';
    end if;
    v_rate := coalesce(v_old.daily_rate, v_row.daily_rate);
    if v_rate is null or v_rate < 0 or v_rate > 9999999999.99 then raise exception 'Enter a valid daily rate.'; end if;
    v_gross := round(v_row.days_worked * v_rate, 2);
    if v_old.id is not null and v_row.days_worked = coalesce(v_old.days_worked, round(v_old.amount / nullif(v_rate, 0), 1)) then v_gross := v_old.amount; end if;
    if v_row.excluded then v_gross := 0; v_row.days_worked := 0; v_row.personal_deduction := 0; end if;
    if v_row.personal_deduction is null or v_row.personal_deduction < 0 or v_row.personal_deduction > v_gross then raise exception 'Loan deductions must be between zero and the weekly wage.'; end if;
    if v_row.personal_deduction > 0 then
      select coalesce(sum(case when kind = 'advance' then amount else -amount end), 0) into v_balance from public.worker_loans where user_id = v_user and worker_id = v_row.worker_id;
      if v_row.personal_deduction > v_balance then raise exception 'Deduction exceeds the worker’s loan balance.'; end if;
      insert into public.worker_loans (user_id, worker_id, loan_date, amount, kind, notes) values (v_user, v_row.worker_id, p_week_start, v_row.personal_deduction, 'repayment', 'Repayment recorded with weekly payment');
    end if;
    insert into public.weekly_payments (user_id, worker_id, week_start, amount, excluded, days_worked, daily_rate, loan_deduction)
      values (v_user, v_row.worker_id, p_week_start, v_gross, coalesce(v_row.excluded, false), v_row.days_worked, v_rate, v_row.personal_deduction)
      on conflict (worker_id, week_start) do update set amount = excluded.amount, excluded = excluded.excluded,
        days_worked = excluded.days_worked, daily_rate = excluded.daily_rate, loan_deduction = excluded.loan_deduction;
  end loop;
  -- Partial saves retain their existing payment behaviour, but are not complete.
  if not exists (
    select 1 from public.workers w where w.user_id = v_user
      and (w.active or exists (select 1 from public.weekly_payments p where p.user_id = v_user and p.worker_id = w.id and p.week_start = p_week_start))
      and not (w.id = any(v_worker_ids))
  ) then
    insert into public.weekly_pay_runs (user_id, week_start, worker_ids) values (v_user, p_week_start, v_worker_ids)
      on conflict (user_id, week_start) do update set worker_ids = excluded.worker_ids, completed_at = now();
  end if;
end;
$$;
revoke all on function public.save_weekly_labour(date, jsonb) from public;
grant execute on function public.save_weekly_labour(date, jsonb) to authenticated;

create or replace function public.clear_weekly_labour(p_week_start date)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare v_user uuid := auth.uid();
begin
  if v_user is null then raise exception 'Please sign in again.'; end if;
  if p_week_start is null or extract(isodow from p_week_start) <> 3 then raise exception 'Choose a Wednesday payment date.'; end if;
  perform id from public.workers where user_id = v_user order by id for update;
  delete from public.worker_loans where user_id = v_user and loan_date = p_week_start and kind = 'repayment' and notes = 'Repayment recorded with weekly payment';
  delete from public.weekly_payments where user_id = v_user and week_start = p_week_start;
  delete from public.weekly_pay_runs where user_id = v_user and week_start = p_week_start;
end;
$$;
revoke all on function public.clear_weekly_labour(date) from public;
grant execute on function public.clear_weekly_labour(date) to authenticated;

-- Service-only atomic enqueue and claim. One run per account/Wednesday/device,
-- with a one-hour catch-up window. Edits/enables after a slot never send it late.
create function public.claim_due_advance_reminders(p_limit integer default 30)
returns table (delivery_id uuid, owner_id uuid, week_start date, subscription_id uuid, endpoint text, p256dh text, auth text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_now timestamptz := now();
begin
  -- A crash/network ambiguity cannot safely be retried: the push may already
  -- have been accepted. Keep it uncertain rather than sending a duplicate.
  update public.advance_reminder_deliveries set status = 'uncertain'
    where status = 'sending' and claimed_at < v_now - interval '5 minutes';
  update public.advance_reminder_deliveries d set status = 'cancelled'
    where d.status in ('pending', 'retry') and (
      not exists (select 1 from public.advance_reminder_settings s where s.user_id = d.user_id and s.enabled and s.updated_at <= d.scheduled_at)
      or exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
    );
  update public.advance_reminder_deliveries set status = 'expired'
    where status in ('pending', 'retry') and scheduled_at + interval '1 hour' <= v_now;
  insert into public.advance_reminder_deliveries (user_id, week_start, subscription_id, endpoint, scheduled_at)
  select s.user_id, slot.pay_week, p.id, p.endpoint, slot.due_at
  from public.advance_reminder_settings s
  cross join lateral (
    select (v_now at time zone s.timezone)::date - ((extract(dow from v_now at time zone s.timezone)::integer - s.weekday + 7) % 7) as reminder_date
  ) d
  cross join lateral (
    select (d.reminder_date + s.reminder_time) at time zone s.timezone as due_at,
      d.reminder_date - ((extract(dow from d.reminder_date)::integer + 4) % 7) as pay_week
  ) slot
  join public.advance_push_subscriptions p on p.user_id = s.user_id
  where s.enabled and s.updated_at <= slot.due_at and v_now >= slot.due_at and v_now < slot.due_at + interval '1 hour'
    and (p.expiration_time is null or p.expiration_time > v_now)
    and not exists (select 1 from public.weekly_pay_runs r where r.user_id = s.user_id and r.week_start = slot.pay_week)
    and exists (select 1 from public.workers w where w.user_id = s.user_id and (w.active or exists (select 1 from public.weekly_payments wp where wp.user_id = s.user_id and wp.worker_id = w.id and wp.week_start = slot.pay_week)))
  on conflict on constraint advance_reminder_deliveries_user_id_week_start_endpoint_key do nothing;

  return query
  with candidates as (
    select d.id from public.advance_reminder_deliveries d
    join public.advance_reminder_settings s on s.user_id = d.user_id
    join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id
    where d.status in ('pending', 'retry') and d.next_attempt_at <= v_now and d.attempt_count < 3
      and s.enabled and s.updated_at <= d.scheduled_at and v_now < d.scheduled_at + interval '1 hour'
      and (p.expiration_time is null or p.expiration_time > v_now)
      and not exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
    order by d.scheduled_at, d.id limit least(greatest(p_limit, 1), 100)
    for update of d skip locked
  ), claimed as (
    update public.advance_reminder_deliveries d set status = 'sending', claimed_at = v_now, attempt_count = d.attempt_count + 1
      from candidates c where d.id = c.id returning d.*
  )
  select d.id, d.user_id, d.week_start, p.id, p.endpoint, p.p256dh, p.auth
    from claimed d join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id;
end;
$$;
revoke all on function public.claim_due_advance_reminders(integer) from public, anon, authenticated;
grant execute on function public.claim_due_advance_reminders(integer) to service_role;

create function public.finish_advance_reminder(p_id uuid, p_status text, p_http_status integer default null)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if p_status not in ('sent', 'retry', 'uncertain', 'expired', 'cancelled') then raise exception 'Invalid delivery result.'; end if;
  update public.advance_reminder_deliveries set
    status = case when p_status = 'retry' and (attempt_count >= 3 or now() + interval '5 minutes' >= scheduled_at + interval '1 hour') then 'expired' else p_status end,
    next_attempt_at = now() + interval '5 minutes',
    sent_at = case when p_status = 'sent' then now() else sent_at end,
    last_http_status = p_http_status
  where id = p_id and status = 'sending';
end;
$$;
revoke all on function public.finish_advance_reminder(uuid, text, integer) from public, anon, authenticated;
grant execute on function public.finish_advance_reminder(uuid, text, integer) to service_role;

-- Explicit test alerts are separate from the scheduled ledger and rate limited.
create function public.claim_advance_reminder_test(p_user_id uuid, p_endpoint text)
returns boolean language plpgsql security definer set search_path = public, pg_temp as $$
declare v_id uuid;
begin
  update public.advance_push_subscriptions set last_test_at = now()
    where user_id = p_user_id and endpoint = p_endpoint and (last_test_at is null or last_test_at < now() - interval '1 minute')
    returning id into v_id;
  return v_id is not null;
end;
$$;
revoke all on function public.claim_advance_reminder_test(uuid, text) from public, anon, authenticated;
grant execute on function public.claim_advance_reminder_test(uuid, text) to service_role;
$reminder_1$;
  end if;

  -- Check all markers together: a partially edited daily schema is unsafe to
  -- guess at. Clean older installations have none; upgraded ones have all nine.
  select count(*) into v_daily_count from unnest(array[
    exists (select 1 from pg_attribute where attrelid = 'public.advance_reminder_settings'::regclass and attname = 'revision' and not attisdropped),
    exists (select 1 from pg_attribute where attrelid = 'public.advance_reminder_deliveries'::regclass and attname = 'kind' and not attisdropped),
    exists (select 1 from pg_attribute where attrelid = 'public.advance_reminder_deliveries'::regclass and attname = 'settings_revision' and not attisdropped),
    to_regclass('public.advance_reminder_weeks') is not null,
    exists (select 1 from pg_constraint where conrelid = 'public.advance_reminder_deliveries'::regclass and conname = 'advance_reminder_delivery_occurrence_key' and contype = 'u'),
    to_regprocedure('public.prepare_advance_reminder_settings()') is not null,
    to_regprocedure('public.queue_advance_reminder_reschedule()') is not null,
    exists (select 1 from pg_trigger where tgrelid = 'public.advance_reminder_settings'::regclass and tgname = 'advance_reminder_settings_updated' and tgfoid = to_regprocedure('public.prepare_advance_reminder_settings()') and not tgisinternal and tgenabled <> 'D'),
    exists (select 1 from pg_trigger where tgrelid = 'public.advance_reminder_settings'::regclass and tgname = 'advance_reminder_rescheduled' and tgfoid = to_regprocedure('public.queue_advance_reminder_reschedule()') and not tgisinternal and tgenabled <> 'D')
  ]) as marker(installed) where marker.installed;

  if v_daily_count not in (0, 9) then
    raise exception 'The daily reminder schema is partially installed. No changes were applied. Inspect migration 202610050003_repeating_advance_reminders.sql before upgrading.';
  end if;
  if v_daily_count = 9 and exists (
    select 1 from pg_constraint where conrelid = 'public.advance_reminder_deliveries'::regclass
      and conname = 'advance_reminder_deliveries_user_id_week_start_endpoint_key'
  ) then
    raise exception 'The old weekly delivery constraint still exists. The daily reminder migration is incomplete; no changes were applied.';
  end if;

  if not exists (
    select 1 from pg_attribute where attrelid = 'public.advance_push_subscriptions'::regclass
      and attname = 'connected_at' and not attisdropped and attnotnull
  ) then
    if v_daily_count <> 0 then
      raise exception 'The daily reminder schema is missing its phone connection prerequisite. No changes were applied.';
    end if;
    execute $reminder_2$
-- A phone connected after a reminder slot starts with the next occurrence.
-- Apply after 202610050001_advance_reminders.sql. Existing phones retain their
-- creation timestamp; reconnecting the same subscription preserves this value.

alter table public.advance_push_subscriptions add column if not exists connected_at timestamptz;
update public.advance_push_subscriptions set connected_at = created_at where connected_at is null;
alter table public.advance_push_subscriptions alter column connected_at set default now();
alter table public.advance_push_subscriptions alter column connected_at set not null;

create or replace function public.claim_due_advance_reminders(p_limit integer default 30)
returns table (delivery_id uuid, owner_id uuid, week_start date, subscription_id uuid, endpoint text, p256dh text, auth text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_now timestamptz := now();
begin
  -- A crash/network ambiguity cannot safely be retried: the push may already
  -- have been accepted. Keep it uncertain rather than sending a duplicate.
  update public.advance_reminder_deliveries set status = 'uncertain'
    where status = 'sending' and claimed_at < v_now - interval '5 minutes';
  update public.advance_reminder_deliveries d set status = 'cancelled'
    where d.status in ('pending', 'retry') and (
      not exists (select 1 from public.advance_reminder_settings s where s.user_id = d.user_id and s.enabled and s.updated_at <= d.scheduled_at)
      or exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
    );
  update public.advance_reminder_deliveries set status = 'expired'
    where status in ('pending', 'retry') and scheduled_at + interval '1 hour' <= v_now;
  insert into public.advance_reminder_deliveries (user_id, week_start, subscription_id, endpoint, scheduled_at)
  select s.user_id, slot.pay_week, p.id, p.endpoint, slot.due_at
  from public.advance_reminder_settings s
  cross join lateral (
    select (v_now at time zone s.timezone)::date - ((extract(dow from v_now at time zone s.timezone)::integer - s.weekday + 7) % 7) as reminder_date
  ) d
  cross join lateral (
    select (d.reminder_date + s.reminder_time) at time zone s.timezone as due_at,
      d.reminder_date - ((extract(dow from d.reminder_date)::integer + 4) % 7) as pay_week
  ) slot
  join public.advance_push_subscriptions p on p.user_id = s.user_id
  where s.enabled and s.updated_at <= slot.due_at and v_now >= slot.due_at and v_now < slot.due_at + interval '1 hour'
    and p.connected_at <= slot.due_at
    and (p.expiration_time is null or p.expiration_time > v_now)
    and not exists (select 1 from public.weekly_pay_runs r where r.user_id = s.user_id and r.week_start = slot.pay_week)
    and exists (select 1 from public.workers w where w.user_id = s.user_id and (w.active or exists (select 1 from public.weekly_payments wp where wp.user_id = s.user_id and wp.worker_id = w.id and wp.week_start = slot.pay_week)))
  on conflict on constraint advance_reminder_deliveries_user_id_week_start_endpoint_key do nothing;

  return query
  with candidates as (
    select d.id from public.advance_reminder_deliveries d
    join public.advance_reminder_settings s on s.user_id = d.user_id
    join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id
    where d.status in ('pending', 'retry') and d.next_attempt_at <= v_now and d.attempt_count < 3
      and s.enabled and s.updated_at <= d.scheduled_at and v_now < d.scheduled_at + interval '1 hour'
      and p.connected_at <= d.scheduled_at
      and (p.expiration_time is null or p.expiration_time > v_now)
      and not exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
    order by d.scheduled_at, d.id limit least(greatest(p_limit, 1), 100)
    for update of d skip locked
  ), claimed as (
    update public.advance_reminder_deliveries d set status = 'sending', claimed_at = v_now, attempt_count = d.attempt_count + 1
      from candidates c where d.id = c.id returning d.*
  )
  select d.id, d.user_id, d.week_start, p.id, p.endpoint, p.p256dh, p.auth
    from claimed d join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id;
end;
$$;
revoke all on function public.claim_due_advance_reminders(integer) from public, anon, authenticated;
grant execute on function public.claim_due_advance_reminders(integer) to service_role;
$reminder_2$;
  end if;

  if v_daily_count = 0 then
    execute $reminder_3$
-- Daily reminders for each pending pay week, plus transactional reschedule alerts.
-- Apply after 202610050002_reminder_phone_connections.sql.

alter table public.advance_reminder_settings add column revision bigint not null default 1;
alter table public.advance_reminder_deliveries
  add column kind text not null default 'payment' check (kind in ('payment', 'rescheduled')),
  add column settings_revision bigint not null default 1;
alter table public.advance_reminder_deliveries
  drop constraint advance_reminder_deliveries_user_id_week_start_endpoint_key,
  add constraint advance_reminder_delivery_occurrence_key unique (user_id, week_start, endpoint, kind, scheduled_at, settings_revision);

-- Retain a week's identity after the next Wednesday. Only weeks whose reminder
-- has actually started are tracked; old missing payments are not backfilled.
create table public.advance_reminder_weeks (
  user_id uuid not null references public.advance_reminder_settings(user_id) on delete cascade,
  week_start date not null check (extract(isodow from week_start) = 3),
  starts_at timestamptz not null,
  primary key (user_id, week_start)
);
alter table public.advance_reminder_weeks enable row level security;
create policy "Read own pending reminder weeks" on public.advance_reminder_weeks
  for select to authenticated using (user_id = auth.uid());
revoke all on public.advance_reminder_weeks from public, anon, authenticated;
grant select on public.advance_reminder_weeks to authenticated;
grant all on public.advance_reminder_weeks to service_role;
insert into public.advance_reminder_weeks (user_id, week_start, starts_at)
select d.user_id, d.week_start, min(d.scheduled_at)
from public.advance_reminder_deliveries d
join public.advance_reminder_settings s on s.user_id = d.user_id
where not exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
group by d.user_id, d.week_start;

-- A revision cancels stale in-flight claims even when edits happen in the same
-- transaction. Unchanged saves and connections never restart the schedule.
create function public.prepare_advance_reminder_settings() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if (new.enabled, new.weekday, new.reminder_time, new.timezone)
    is distinct from (old.enabled, old.weekday, old.reminder_time, old.timezone) then
    new.updated_at := now();
    new.revision := old.revision + 1;
  else
    new.updated_at := old.updated_at;
    new.revision := old.revision;
  end if;
  return new;
end;
$$;
revoke all on function public.prepare_advance_reminder_settings() from public;
drop trigger advance_reminder_settings_updated on public.advance_reminder_settings;
create trigger advance_reminder_settings_updated before update on public.advance_reminder_settings
  for each row execute function public.prepare_advance_reminder_settings();

create function public.queue_advance_reminder_reschedule() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_local date := (new.updated_at at time zone new.timezone)::date;
  v_start timestamptz;
  v_week date := v_local - ((extract(dow from v_local)::integer + 4) % 7);
begin
  if new.revision = old.revision then return null; end if;
  update public.advance_reminder_deliveries set status = 'cancelled'
    where user_id = new.user_id and status in ('pending', 'retry');
  if not new.enabled then return null; end if;

  -- Rescheduling/re-enabling restarts pending weeks at the next selected day
  -- and time. Their original Wednesday payment dates remain unchanged.
  v_start := (v_local + ((new.weekday - extract(dow from v_local)::integer + 7) % 7) + new.reminder_time) at time zone new.timezone;
  if v_start < new.updated_at then v_start := v_start + interval '7 days'; end if;
  update public.advance_reminder_weeks set starts_at = v_start where user_id = new.user_id;

  if (new.weekday, new.reminder_time) is distinct from (old.weekday, old.reminder_time) then
    insert into public.advance_reminder_deliveries (user_id, week_start, subscription_id, endpoint, scheduled_at, kind, settings_revision)
    select new.user_id, v_week, p.id, p.endpoint, new.updated_at, 'rescheduled', new.revision
    from public.advance_push_subscriptions p
    where p.user_id = new.user_id and p.connected_at <= new.updated_at
      and (p.expiration_time is null or p.expiration_time > new.updated_at)
    on conflict on constraint advance_reminder_delivery_occurrence_key do nothing;
  end if;
  return null;
end;
$$;
revoke all on function public.queue_advance_reminder_reschedule() from public;
create trigger advance_reminder_rescheduled after update on public.advance_reminder_settings
  for each row execute function public.queue_advance_reminder_reschedule();

create or replace function public.claim_due_advance_reminders(p_limit integer default 30)
returns table (delivery_id uuid, owner_id uuid, week_start date, subscription_id uuid, endpoint text, p256dh text, auth text)
language plpgsql security definer set search_path = public, pg_temp as $$
declare v_now timestamptz := now();
begin
  update public.advance_reminder_deliveries set status = 'uncertain'
    where status = 'sending' and claimed_at < v_now - interval '5 minutes';
  update public.advance_reminder_deliveries d set status = 'cancelled'
    where d.status in ('pending', 'retry') and (
      not exists (select 1 from public.advance_reminder_settings s where s.user_id = d.user_id and s.enabled and s.revision = d.settings_revision and s.updated_at <= d.scheduled_at)
      or (d.kind = 'payment' and exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start))
    );
  update public.advance_reminder_deliveries set status = 'expired'
    where status in ('pending', 'retry') and scheduled_at + interval '1 hour' <= v_now;
  delete from public.advance_reminder_weeks w
    where exists (select 1 from public.weekly_pay_runs r where r.user_id = w.user_id and r.week_start = w.week_start);

  -- Track the selected weekly occurrence even if cron missed its first slot.
  -- Only the latest daily slot may send; no past notification is sent late.
  insert into public.advance_reminder_weeks (user_id, week_start, starts_at)
  select s.user_id, slot.pay_week, slot.due_at
  from public.advance_reminder_settings s
  cross join lateral (
    select (v_now at time zone s.timezone)::date - ((extract(dow from v_now at time zone s.timezone)::integer - s.weekday + 7) % 7) as reminder_date
  ) d
  cross join lateral (
    select (d.reminder_date + s.reminder_time) at time zone s.timezone as due_at,
      d.reminder_date - ((extract(dow from d.reminder_date)::integer + 4) % 7) as pay_week
  ) slot
  where s.enabled and s.updated_at <= slot.due_at and v_now >= slot.due_at
    and not exists (select 1 from public.weekly_pay_runs r where r.user_id = s.user_id and r.week_start = slot.pay_week)
    and exists (select 1 from public.workers w where w.user_id = s.user_id and (w.active or exists (select 1 from public.weekly_payments wp where wp.user_id = s.user_id and wp.worker_id = w.id and wp.week_start = slot.pay_week)))
  on conflict on constraint advance_reminder_weeks_pkey do nothing;

  -- Most recent India-local daily slot (including catch-up across midnight).
  insert into public.advance_reminder_deliveries (user_id, week_start, subscription_id, endpoint, scheduled_at, settings_revision)
  select s.user_id, w.week_start, p.id, p.endpoint, slot.due_at, s.revision
  from public.advance_reminder_settings s
  join public.advance_reminder_weeks w on w.user_id = s.user_id
  cross join lateral (select ((v_now at time zone s.timezone)::date + s.reminder_time) at time zone s.timezone as today_at) t
  cross join lateral (select case when t.today_at > v_now then t.today_at - interval '1 day' else t.today_at end as due_at) slot
  join public.advance_push_subscriptions p on p.user_id = s.user_id
  where s.enabled and s.updated_at <= slot.due_at and w.starts_at <= slot.due_at
    and v_now >= slot.due_at and v_now < slot.due_at + interval '1 hour'
    and p.connected_at <= slot.due_at and (p.expiration_time is null or p.expiration_time > v_now)
    and not exists (select 1 from public.weekly_pay_runs r where r.user_id = s.user_id and r.week_start = w.week_start)
    and exists (select 1 from public.workers worker where worker.user_id = s.user_id and (worker.active or exists (select 1 from public.weekly_payments wp where wp.user_id = s.user_id and wp.worker_id = worker.id and wp.week_start = w.week_start)))
  on conflict on constraint advance_reminder_delivery_occurrence_key do nothing;

  return query
  with candidates as (
    select d.id from public.advance_reminder_deliveries d
    join public.advance_reminder_settings s on s.user_id = d.user_id
    join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id
    where d.status in ('pending', 'retry') and d.next_attempt_at <= v_now and d.attempt_count < 3
      and s.enabled and s.revision = d.settings_revision and s.updated_at <= d.scheduled_at
      and d.scheduled_at <= v_now and v_now < d.scheduled_at + interval '1 hour'
      and p.connected_at <= d.scheduled_at and (p.expiration_time is null or p.expiration_time > v_now)
      and (d.kind = 'rescheduled' or (
        not exists (select 1 from public.weekly_pay_runs r where r.user_id = d.user_id and r.week_start = d.week_start)
        and exists (select 1 from public.workers worker where worker.user_id = d.user_id and (worker.active or exists (select 1 from public.weekly_payments wp where wp.user_id = d.user_id and wp.worker_id = worker.id and wp.week_start = d.week_start)))
      ))
    order by d.scheduled_at, d.id limit least(greatest(p_limit, 1), 100)
    for update of d skip locked
  ), claimed as (
    update public.advance_reminder_deliveries d set status = 'sending', claimed_at = v_now, attempt_count = d.attempt_count + 1
      from candidates c where d.id = c.id returning d.*
  )
  select d.id, d.user_id, d.week_start, p.id, p.endpoint, p.p256dh, p.auth
    from claimed d join public.advance_push_subscriptions p on p.id = d.subscription_id and p.user_id = d.user_id;
end;
$$;
revoke all on function public.claim_due_advance_reminders(integer) from public, anon, authenticated;
grant execute on function public.claim_due_advance_reminders(integer) to service_role;
$reminder_3$;
  end if;

  execute $reminder_4$
-- Keep already-started unpaid weeks on their daily cycle after a schedule edit.
-- Apply after 202610050003_repeating_advance_reminders.sql.

do $$
begin
  if to_regclass('public.advance_reminder_weeks') is null then
    raise exception 'Apply reminder migration 202610050003_repeating_advance_reminders.sql first, or run supabase/upgrades/advance-reminders.sql to install missing reminder prerequisites and this fix together.';
  end if;
end;
$$;

create or replace function public.queue_advance_reminder_reschedule() returns trigger
language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_local date := (new.updated_at at time zone new.timezone)::date;
  v_start timestamptz;
  v_week date := v_local - ((extract(dow from v_local)::integer + 4) % 7);
begin
  if new.revision = old.revision then return null; end if;
  update public.advance_reminder_deliveries set status = 'cancelled'
    where user_id = new.user_id and status in ('pending', 'retry');
  if not new.enabled then return null; end if;

  -- Tracked weeks have already started repeating. The weekday only determines
  -- the first reminder for new weeks; edits must not pause existing daily ones.
  -- A new time still ahead today can send today, even after the old time sent.
  v_start := (v_local + new.reminder_time) at time zone new.timezone;
  if v_start < new.updated_at then v_start := v_start + interval '1 day'; end if;
  update public.advance_reminder_weeks set starts_at = v_start where user_id = new.user_id;

  if (new.weekday, new.reminder_time) is distinct from (old.weekday, old.reminder_time) then
    insert into public.advance_reminder_deliveries (user_id, week_start, subscription_id, endpoint, scheduled_at, kind, settings_revision)
    select new.user_id, v_week, p.id, p.endpoint, new.updated_at, 'rescheduled', new.revision
    from public.advance_push_subscriptions p
    where p.user_id = new.user_id and p.connected_at <= new.updated_at
      and (p.expiration_time is null or p.expiration_time > new.updated_at)
    on conflict on constraint advance_reminder_delivery_occurrence_key do nothing;
  end if;
  return null;
end;
$$;
revoke all on function public.queue_advance_reminder_reschedule() from public, anon, authenticated;

-- Repair pending weeks postponed by the old trigger. Never replay a past slot
-- or restart completed/disabled reminders; delivery tombstones remain intact.
update public.advance_reminder_weeks w
set starts_at = case when slot.today_at < now() then slot.today_at + interval '1 day' else slot.today_at end
from public.advance_reminder_settings s
cross join lateral (
  select ((now() at time zone s.timezone)::date + s.reminder_time) at time zone s.timezone as today_at
) slot
where w.user_id = s.user_id and s.enabled and w.starts_at > now()
  and not exists (select 1 from public.weekly_pay_runs r where r.user_id = w.user_id and r.week_start = w.week_start);
$reminder_4$;
end;
$estate_reminder_upgrade$;

notify pgrst, 'reload schema';
commit;

select 'Reminder database upgrade complete' as result,
  to_regclass('public.advance_reminder_weeks') is not null as daily_tracking_ready,
  to_regprocedure('public.queue_advance_reminder_reschedule()') is not null as reschedule_ready;
