// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { FarmIntelligence } from './FarmIntelligence'
import { FarmOnboarding, validateFarmProfile } from './FarmOnboarding'
import { emptyFarmProfile, emptyBlockCrop, type FarmSnapshot, type OfficialUpdate, type MarketPrice } from '../lib/farmIntelligence'
const api=vi.hoisted(()=>({hook:vi.fn()}))
vi.mock('../hooks/useFarmIntelligence',()=>({useFarmIntelligence:api.hook}))
const initial=():FarmSnapshot=>{const profile=emptyFarmProfile();profile.estate.id='estate-a';profile.estate.estate_name='Sample estate';profile.blocks=[{name:'Mixed block',area:6,area_unit:'acre',latitude:null,longitude:null,irrigation_type:null,water_source:null,notes:null,crops:[emptyBlockCrop('COFFEE'),emptyBlockCrop('PEPPER')]}];return {profile,updates:[],prices:[],sources:[],stations:[],observations:[],alerts:[]}}
const update=(patch:Partial<OfficialUpdate>={}):OfficialUpdate=>({id:'u1',source_id:'coffee-board-news',source_name:'Coffee Board',source_url:'https://coffeeboard.gov.in/News.aspx',source_type:'official',source_authority_level:1,retrieved_at:'2026-10-07T01:00:00Z',source_published_at:'2026-09-07',source_updated_at:null,effective_from:null,effective_until:null,financial_year:null,season:null,raw_source_reference:'Test',verification_status:'OFFICIAL_CONFIRMED',title:'Arabica hybrid announcement',summary:'Two Arabica hybrids announced.',category:'government',crops:['COFFEE'],state:null,district:null,taluk:null,village:null,application_deadline:null,application_url:null,dedupe_key:'a'.repeat(64),details:{notice_subject:'arabica_hybrids'},...patch})
const price=(patch:Partial<MarketPrice>={}):MarketPrice=>({id:'p1',source_id:'spices-board-prices',crop:'PEPPER',variety:null,grade:'Garbled',market:'Cochin',district:null,state:'Kerala',min_price:null,max_price:null,modal_price:null,average_price:723,unit:'INR/kg',price_date:'2026-10-05',price_kind:'indicative',source_url:'https://www.indianspices.com/',retrieved_at:'2026-10-07T01:00:00Z',...patch})
beforeEach(()=>{
  vi.clearAllMocks();vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-07T02:00:00Z'))
  Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.setAttribute('open','')}})
  Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.removeAttribute('open')}})
  api.hook.mockReturnValue({snapshot:initial(),loading:false,saving:false,setupReady:true,error:'',refresh:vi.fn(),save:vi.fn(),markRead:vi.fn()})
})
afterEach(()=>{cleanup();vi.useRealTimers()})
describe('Farm Intelligence safe presentation',()=>{
  it('shows unavailable official observations and no estimated claim for every crop',()=>{
    render(<FarmIntelligence userId="owner-a"/>)
    expect(screen.getByText(/Official Karnataka rainfall data is unavailable/)).toBeTruthy()
    expect(screen.getAllByText('Claim calculation unavailable')).toHaveLength(3)
    expect(screen.getAllByText('Policy status: Unknown')).toHaveLength(3)
    expect(screen.getByText('No matching notices right now')).toBeTruthy()
  })
  it('filters per crop without inventing prices or removing insurance uncertainty',async()=>{
    const user=userEvent.setup();render(<FarmIntelligence userId="owner-a"/>)
    await user.click(screen.getByRole('button',{name:'Pepper'}))
    expect(screen.getAllByText('Claim calculation unavailable')).toHaveLength(1)
    expect(screen.getByText('No matching notices right now')).toBeTruthy()
  })
  it('renders source confidence and stale quote date while escaping untrusted markup',()=>{
    const snapshot=initial()
    snapshot.updates=[update({summary:'<img src=x onerror=alert(1)>',application_url:'javascript:alert(1)'})]
    snapshot.prices=[price({crop:'COFFEE',variety:'Arabica',grade:'Dec-2026',average_price:292.55,unit:'US cents/lb',price_date:'2026-06-05',price_kind:'futures'})]
    api.hook.mockReturnValue({...api.hook(),snapshot})
    const {container}=render(<FarmIntelligence userId="owner-a"/>)
    expect(screen.getByText(/1 contracts · quote 5 Jun 2026 · Stale/)).toBeTruthy()
    expect(screen.getByText('292.55 US cents/lb')).toBeTruthy()
    expect(container.querySelector('img')).toBeNull();expect(container.querySelector('a[href^="javascript:"]')).toBeNull()
    expect(screen.getByText('<img src=x onerror=alert(1)>')).toBeTruthy()
    expect(container.querySelector('.fi-futures')?.hasAttribute('open')).toBe(false)
  })
  it('shows useful regional weather, prices and notices before an estate exists without implying personalization',()=>{
    const snapshot=initial();snapshot.profile=null;snapshot.prices=[price()]
    snapshot.updates=[update(),update({id:'weather',title:'IMD Hassan thunderstorm and lightning warning',summary:'Thunderstorm and lightning',category:'weather',crops:['COFFEE','PEPPER','ARECANUT'],district:'Hassan',state:'Karnataka',effective_from:'2026-10-07',effective_until:'2026-10-07',details:{warning_colour:'yellow'}}),update({id:'nta',title:'Non traditional scheme',category:'schemes',details:{scope:'non_traditional_area'}})]
    api.hook.mockReturnValue({...api.hook(),snapshot})
    const {container}=render(<FarmIntelligence userId="owner-a"/>)
    expect(container.firstElementChild?.classList.contains('page')).toBe(true)
    expect(screen.getByText('REGIONAL OVERVIEW')).toBeTruthy()
    expect(screen.getByText('₹723')).toBeTruthy()
    expect(screen.getByText('thunderstorm and lightning warning')).toBeTruthy()
    expect(screen.getByText('Arabica hybrid announcement')).toBeTruthy()
    expect(screen.getByText(/If you are planning Arabica planting/)).toBeTruthy()
    expect(screen.queryByText('Non traditional scheme')).toBeNull()
    expect(screen.queryByText('Why this appears for your estate')).toBeNull()
    expect(screen.queryByRole('button',{name:'Mark read'})).toBeNull()
    expect(api.hook().save).not.toHaveBeenCalled()
    expect(container.querySelector('.fi-sources')?.hasAttribute('open')).toBe(false)
  })
  it('saves only the entered block and selected crops, preserving unknown areas and policy details',async()=>{
    const snapshot=initial();snapshot.profile=null;const save=vi.fn().mockResolvedValue(undefined)
    api.hook.mockReturnValue({...api.hook(),snapshot,save})
    const user=userEvent.setup();render(<FarmIntelligence userId="owner-a"/>)
    const form=within(screen.getByRole('form',{name:'Quick estate setup'}))
    await user.type(form.getByLabelText('First block name'),'Upper block')
    await user.click(form.getByRole('checkbox',{name:'Coffee'}));await user.click(form.getByRole('checkbox',{name:'Pepper'}))
    await user.click(form.getByRole('button',{name:'Save my estate'}))
    expect(save).toHaveBeenCalledTimes(1)
    expect(save.mock.calls[0][0]).toMatchObject({estate:{state:'Karnataka',district:'Hassan',taluk:'Sakleshpur',total_area:null,latitude:null},blocks:[{name:'Upper block',area:null,crops:[{crop:'COFFEE',coffee_type:null,area:null},{crop:'PEPPER',is_intercrop:null,area:null}]}],insurance:[{crop:'COFFEE',currently_insured:null},{crop:'PEPPER',currently_insured:null},{crop:'ARECANUT',currently_insured:null}]})
  })
  it('requires crop presence and retains quick setup inputs when saving fails',async()=>{
    const snapshot=initial();snapshot.profile=null;const save=vi.fn().mockRejectedValue(new Error('Could not save'))
    api.hook.mockReturnValue({...api.hook(),snapshot,save})
    const user=userEvent.setup();render(<FarmIntelligence userId="owner-a"/>)
    const form=within(screen.getByRole('form',{name:'Quick estate setup'}))
    await user.type(form.getByLabelText('First block name'),'Upper block')
    await user.click(form.getByRole('button',{name:'Save my estate'}))
    expect(save).not.toHaveBeenCalled();expect(screen.getByRole('alert').textContent).toContain('Select at least one crop')
    await user.click(form.getByRole('checkbox',{name:'Coffee'}));await user.click(form.getByRole('button',{name:'Save my estate'}))
    expect(screen.getByRole('alert').textContent).toContain('Could not save')
    expect((form.getByLabelText('First block name') as HTMLInputElement).value).toBe('Upper block')
  })
  it('carries quick setup inputs into the full profile editor',async()=>{
    const snapshot=initial();snapshot.profile=null;api.hook.mockReturnValue({...api.hook(),snapshot})
    const user=userEvent.setup();render(<FarmIntelligence userId="owner-a"/>)
    const form=within(screen.getByRole('form',{name:'Quick estate setup'}))
    await user.type(form.getByLabelText('First block name'),'Lower block')
    await user.click(form.getByRole('checkbox',{name:'Arecanut'}));await user.click(form.getByRole('button',{name:'Full profile setup'}))
    const dialog=within(screen.getByRole('dialog'))
    await user.click(dialog.getByRole('button',{name:'Farm blocks'}))
    expect((dialog.getByLabelText('Block name') as HTMLInputElement).value).toBe('Lower block')
    await user.click(dialog.getByRole('button',{name:'Arecanut'}))
    expect(dialog.getByText(/Arecanut · variety/)).toBeTruthy()
  })
  it('keeps completed notices out of the current feed and shows separate history',async()=>{
    const snapshot=initial()
    snapshot.updates=[{id:'old',source_id:'coffee-board-news',source_name:'Coffee Board',source_url:'https://coffeeboard.gov.in/News.aspx',source_type:'official',source_authority_level:1,retrieved_at:'2026-10-07T01:00:00Z',source_published_at:'2026-02-02',source_updated_at:null,effective_from:'2026-03-02',effective_until:'2026-03-06',financial_year:null,season:null,raw_source_reference:'Test expired',verification_status:'EXPIRED',title:'Completed test training',summary:'Expired fixture',category:'training',crops:['COFFEE'],state:null,district:null,taluk:null,village:null,application_deadline:null,application_url:null,dedupe_key:'b'.repeat(64),details:{}}]
    api.hook.mockReturnValue({...api.hook(),snapshot})
    render(<FarmIntelligence userId="owner-a"/>)
    expect(screen.queryByText('Completed test training')).toBeNull()
    await userEvent.setup().click(screen.getByLabelText('View expired notices separately'))
    expect(screen.getByText('Completed test training')).toBeTruthy()
  })
})
describe('nine-step estate setup',()=>{
  it('skips unknown steps while preserving separate policy nulls and multiple survey numbers',async()=>{
    const user=userEvent.setup(),save=vi.fn().mockResolvedValue(undefined),close=vi.fn()
    render(<FarmOnboarding initial={null} saving={false} onSave={save} onClose={close}/>)
    await user.type(screen.getByLabelText('Estate name'),'Test estate')
    await user.type(screen.getByLabelText(/Survey numbers/),'10/1, 10/2')
    for(let step=0;step<8;step++)await user.click(screen.getByRole('button',{name:'Skip for now'}))
    await user.click(screen.getByRole('button',{name:'Save estate profile'}))
    expect(save).toHaveBeenCalledWith(expect.objectContaining({estate:expect.objectContaining({estate_name:'Test estate',latitude:null,longitude:null,survey_numbers:['10/1','10/2']}),blocks:[],insurance:expect.arrayContaining([expect.objectContaining({crop:'COFFEE',currently_insured:null}),expect.objectContaining({crop:'PEPPER',currently_insured:null}),expect.objectContaining({crop:'ARECANUT',currently_insured:null})])}))
    expect(close).toHaveBeenCalledTimes(1)
  })
  it('adds coffee and intercropped pepper to the same physical block',async()=>{
    const user=userEvent.setup(),save=vi.fn().mockResolvedValue(undefined)
    render(<FarmOnboarding initial={null} saving={false} onSave={save} onClose={vi.fn()}/>)
    await user.type(screen.getByLabelText('Total estate area'),'6')
    await user.click(screen.getByRole('button',{name:'Next'}))
    await user.click(screen.getByRole('button',{name:'Add a physical block'}))
    await user.type(screen.getByLabelText('Physical block area'),'6')
    await user.click(screen.getByRole('button',{name:'Next'}))
    await user.click(screen.getByRole('button',{name:'Add coffee'}))
    await user.selectOptions(screen.getByLabelText('Coffee type'),'Arabica')
    await user.type(screen.getByLabelText('Crop area'),'6')
    await user.click(screen.getByRole('button',{name:'Next'}))
    await user.click(screen.getByRole('button',{name:'Add pepper'}))
    await user.selectOptions(screen.getByLabelText('Intercropped in this block?'),'true')
    await user.type(screen.getByLabelText('Crop area'),'6')
    for(let step=3;step<8;step++)await user.click(screen.getByRole('button',{name:'Next'}))
    await user.click(screen.getByRole('button',{name:'Save estate profile'}))
    expect(save.mock.calls[0][0].blocks).toHaveLength(1)
    expect(save.mock.calls[0][0].blocks[0]).toMatchObject({area:6,crops:[{crop:'COFFEE',area:6,coffee_type:'Arabica'},{crop:'PEPPER',area:6,is_intercrop:true}]})
  })
  it('retains a draft and displays the error when saving fails',async()=>{
    const save=vi.fn().mockRejectedValue(new Error('Test save failure')),close=vi.fn()
    render(<FarmOnboarding initial={null} saving={false} onSave={save} onClose={close}/>)
    for(let i=0;i<8;i++)fireEvent.click(screen.getByRole('button',{name:'Next'}))
    await act(async()=>fireEvent.submit(screen.getByRole('button',{name:'Save estate profile'}).closest('form')!))
    expect(screen.getByRole('alert').textContent).toContain('Test save failure');expect(close).not.toHaveBeenCalled()
  })
  it('validates physical areas independently from intercropped crop areas',()=>{
    const p=initial().profile!;p.estate.total_area=6;p.blocks[0].crops.forEach(c=>c.area=6)
    expect(validateFarmProfile(p)).toBeNull()
    p.blocks[0].area=7;expect(validateFarmProfile(p)).toContain('physical block')
    p.blocks[0].area=6;p.estate.latitude=12;expect(validateFarmProfile(p)).toContain('both latitude')
  })
})
