import { useState, type FormEvent } from 'react'
import { ChevronLeft, ChevronRight, Plus, Trash2 } from 'lucide-react'
import { Sheet, Notice } from './Workspace'
import { FarmSurveyPicker } from './FarmSurveyPicker'
import { selectionPatch } from '../lib/farmSurveyMap'
import { SQUARE_METRES_PER_ACRE } from '../lib/farmParcelDetails'
import { rtcExtentText } from '../lib/farmRtcClient'
import { CROPS, emptyFarmProfile, emptyBlockCrop, hectares, type FarmProfile, type FarmBlockInput, type BlockCropInput, type Crop } from '../lib/farmIntelligence'

export const CROP_LABELS: Record<Crop,string>={COFFEE:'Coffee',PEPPER:'Pepper',ARECANUT:'Arecanut'}
const steps=['Estate location','Farm blocks','Coffee','Pepper','Arecanut','Water & eligibility','Insurance','Equipment','Alerts']
const water=['borewell','open_well','pond','tank','stream','other'],irrigation=['sprinkler','drip','manual','rainfed','other']
const equipment=['coffee pulper','drying yard','dryer','pepper thresher','sprayer','power sprayer','brush cutter','tractor','mini tractor','power tiller','pumps','sprinkler system','drip system','water tank','farm pond','solar equipment','generator','storage/godown','fencing']
const nice=(value:string)=>value.replaceAll('_',' ').replace(/^./,letter=>letter.toUpperCase())
type FieldSpec<T>={key:keyof T & string;label:string;kind?:'number'|'select'|'boolean';options?:string[];min?:number;max?:number;integer?:boolean;maxLength?:number;required?:boolean;placeholder?:string}
function Fields<T extends object>({value,onPatch,fields}:{value:T;onPatch:(patch:Partial<T>)=>void;fields:FieldSpec<T>[]}) {
  return <div className="fi-fields">{fields.map(field=>{
    const current=(value as Record<string,unknown>)[field.key]
    const change=(raw:string)=>onPatch({[field.key]:field.kind==='number'?(raw===''?null:Number(raw)):field.kind==='boolean'?(raw===''?null:raw==='true'):(raw.trim()===''?null:raw)} as Partial<T>)
    return <label key={field.key}><span>{field.label}</span>{field.kind==='select'||field.kind==='boolean'?<select value={current==null?'':String(current)} onChange={e=>change(e.target.value)}>{field.key!=='area_unit'&&<option value="">I don’t know / skip</option>}{field.kind==='boolean'?<><option value="true">Yes</option><option value="false">No</option></>:field.options?.map(option=><option key={option} value={option}>{nice(option)}</option>)}</select>:<input required={field.required} type={field.kind==='number'?'number':'text'} value={current==null?'':String(current)} onChange={e=>change(e.target.value)} placeholder={field.placeholder ?? (field.required?'Required':'Leave blank if unknown')} min={field.min ?? (field.kind==='number'?0:undefined)} max={field.max} step={field.integer?1:'any'} maxLength={field.maxLength ?? 160} inputMode={field.kind==='number'?'decimal':undefined} />}</label>
  })}</div>
}
function Checks({label,choices,value,onChange}:{label:string;choices:string[];value:string[];onChange:(values:string[])=>void}) {
  return <fieldset className="fi-checks"><legend>{label}</legend>{choices.map(choice=><label key={choice}><input type="checkbox" checked={value.includes(choice)} onChange={e=>onChange(e.target.checked?[...value,choice]:value.filter(item=>item!==choice))} /><span>{nice(choice)}</span></label>)}</fieldset>
}
export function validateFarmProfile(profile:FarmProfile) {
  const estate=profile.estate
  if(!estate.state?.trim()||!estate.district?.trim()||!estate.taluk?.trim()) return 'State, district and taluk are needed for local relevance.'
  if(estate.pincode && !/^\d{6}$/.test(estate.pincode)) return 'Enter a six-digit pincode, or leave it blank.'
  for(const location of [estate,...profile.blocks]) {
    if((location.latitude===null)!==(location.longitude===null)) return 'Enter both latitude and longitude, or leave both unknown.'
    if(location.latitude!==null && (!Number.isFinite(location.latitude)||Math.abs(location.latitude)>90)) return 'Latitude must be between −90 and 90.'
    if(location.longitude!==null && (!Number.isFinite(location.longitude)||Math.abs(location.longitude)>180)) return 'Longitude must be between −180 and 180.'
  }
  if(estate.total_area!==null && estate.cultivated_area!==null && estate.cultivated_area>estate.total_area) return 'Cultivated area exceeds total estate area.'
  if(profile.blocks.some(block=>!block.name.trim())) return 'Give each physical block a name.'
  const blockArea=profile.blocks.reduce((sum,block)=>sum+(block.area===null?0:hectares(block.area,block.area_unit)),0)
  if(estate.total_area!==null && blockArea>hectares(estate.total_area,estate.area_unit)+1e-8) return 'The physical block areas exceed total estate area. Intercropped crops do not add extra land.'
  for(const block of profile.blocks) for(const crop of block.crops) {
    if(crop.number_of_plants!==null && (crop.bearing_plants??0)+(crop.non_bearing_plants??0)>crop.number_of_plants) return `Bearing and non-bearing plants exceed the total in ${block.name}.`
    if(crop.area!==null && (crop.bearing_area??0)+(crop.non_bearing_area??0)>crop.area) return `Bearing and non-bearing area exceed the crop area in ${block.name}.`
    if(block.area!==null && crop.area!==null && hectares(crop.area,crop.area_unit)>hectares(block.area,block.area_unit)+1e-8) return `A crop area exceeds the physical area of ${block.name}.`
  }
  return null
}

export function FarmOnboarding({initial,saving,onSave,onClose}:{initial:FarmProfile|null;saving:boolean;onSave:(profile:FarmProfile)=>Promise<void>;onClose:()=>void}) {
  const [profile,setProfile]=useState<FarmProfile>(()=>structuredClone(initial??emptyFarmProfile())),[step,setStep]=useState(0),[error,setError]=useState('')
  const [surveyText,setSurveyText]=useState(()=>initial?.estate.survey_numbers.join(', ')??'')
  const estate=(patch:Partial<FarmProfile['estate']>)=>{
    const contextChanged=!('location_source' in patch)&&(['state','district','taluk','hobli','village'] as const).some(key=>key in patch&&patch[key]!==profile.estate[key])
    if(contextChanged)setSurveyText('')
    setProfile(p=>({...p,estate:{...p.estate,...patch,...(contextChanged?{latitude:null,longitude:null,elevation_m:null,survey_numbers:[],location_source:null}:!('location_source' in patch)&&('latitude' in patch||'longitude' in patch)?{location_source:null}:{})}}))
  }
  const blockPatch=(index:number,patch:Partial<FarmBlockInput>)=>setProfile(p=>({...p,blocks:p.blocks.map((block,i)=>i===index?{...block,...patch}:block)}))
  function addBlock() { setProfile(p=>({...p,blocks:[...p.blocks,{id:crypto.randomUUID(),name:`Block ${p.blocks.length+1}`,area:null,area_unit:p.estate.area_unit,latitude:null,longitude:null,irrigation_type:null,water_source:null,notes:null,crops:[]}]})) }
  const cropStep=step===2?'COFFEE':step===3?'PEPPER':'ARECANUT'
  function cropsEditor(crop:Crop) {
    const countLabel=crop==='PEPPER'?'vines':crop==='ARECANUT'?'palms':'plants'
    return <><p className="fi-help">Add {CROP_LABELS[crop].toLowerCase()} to each block where it grows. Multiple varieties and intercropping are supported; leave unknown details blank.</p>{!profile.blocks.length&&<button type="button" className="button-secondary" onClick={()=>move(1)}>Add a physical block first</button>}{profile.blocks.map((block,index)=><section key={block.id??index} className="fi-form-card"><div className="fi-card-heading"><h3>{block.name}</h3><button type="button" className="button-secondary" disabled={block.crops.length>=30} onClick={()=>blockPatch(index,{crops:[...block.crops,{...emptyBlockCrop(crop),id:crypto.randomUUID(),area_unit:block.area_unit}]})}><Plus size={16} />Add {CROP_LABELS[crop].toLowerCase()}</button></div>{block.crops.map((item,cropIndex)=>item.crop===crop&&<div className="fi-crop-record" key={item.id??cropIndex}><div className="fi-card-heading"><h4>{CROP_LABELS[crop]} · variety {cropIndex+1}</h4><button type="button" className="icon-button danger" aria-label={`Remove ${CROP_LABELS[crop].toLowerCase()} from ${block.name}`} onClick={()=>blockPatch(index,{crops:block.crops.filter((_,i)=>i!==cropIndex)})}><Trash2 size={16}/></button></div><Fields<BlockCropInput> value={item} onPatch={patch=>blockPatch(index,{crops:block.crops.map((value,i)=>i===cropIndex?{...value,...patch}:value)})} fields={[
      ...(crop==='COFFEE'?[{key:'coffee_type' as const,label:'Coffee type',kind:'select' as const,options:['Arabica','Robusta']}]:[]),
      {key:'variety',label:'Variety'},{key:'area',label:'Crop area',kind:'number'},{key:'area_unit',label:'Area unit',kind:'select',options:['acre','hectare']},
      {key:'planting_year',label:'Planting year',kind:'number',integer:true,min:1800,max:2200},{key:'age_years',label:`Age of ${countLabel} (years)`,kind:'number',max:300},
      {key:'number_of_plants',label:`Total ${countLabel}`,kind:'number',integer:true},{key:'bearing_plants',label:`Bearing ${countLabel}`,kind:'number',integer:true},{key:'non_bearing_plants',label:`Non-bearing ${countLabel}`,kind:'number',integer:true},
      ...(crop==='COFFEE'?[{key:'bearing_area' as const,label:'Bearing area',kind:'number' as const},{key:'non_bearing_area' as const,label:'Non-bearing area',kind:'number' as const},{key:'processing_type' as const,label:'Processing',kind:'select' as const,options:['cherry','parchment','both']}]:[]),
      ...(crop==='PEPPER'?[{key:'support_tree_type' as const,label:'Support tree type'}]:[]),{key:'is_intercrop',label:'Intercropped in this block?',kind:'boolean'},
      {key:'estimated_annual_production',label:'Estimated annual production',kind:'number'},{key:'production_unit',label:'Production unit (e.g. kg)',maxLength:40}
    ]}/></div>)}</section>)}</>
  }
  async function submit(event:FormEvent) {
    event.preventDefault();const invalid=validateFarmProfile(profile);if(invalid){setError(invalid);return}
    setError('');try{await onSave({...profile,estate:{...profile.estate,survey_numbers:surveyText.split(',').map(value=>value.trim()).filter(Boolean)}});onClose()}catch(e){setError(e instanceof Error?e.message:'Could not save your profile.')}
  }
  function move(next:number) {setError('');setStep(next)}
  return <Sheet open title={initial?'Edit estate profile':'Set up your estate'} wide busy={saving} onClose={onClose} className="fi-onboarding"><form onSubmit={submit} aria-busy={saving}><fieldset disabled={saving} className="fi-wizard-content">
    <div className="fi-step-heading"><span>STEP {step+1} OF {steps.length}</span><strong>{steps[step]}</strong><progress value={step+1} max={steps.length} aria-label="Profile setup progress" /></div>
    <nav className="fi-step-nav" aria-label="Estate profile sections">{steps.map((label,index)=><button key={label} type="button" aria-current={step===index?'step':undefined} onClick={()=>move(index)}>{label}</button>)}</nav>
    <p className="fi-help">Your profile is private to your account. Each optional detail can be skipped and edited later.</p>
    {step===0&&<><FarmSurveyPicker onSelect={selection=>{const patch=selectionPatch(selection);estate(patch);setSurveyText(patch.survey_numbers!.join(', '))}}/>{profile.estate.location_source&&<p className="fi-help">KGIS {profile.estate.location_source.level==='hissa'?'subdivision':'whole-survey'} map point selected. Coordinates describe a point inside that mapped parcel; elevation and crop details remain unknown.</p>}{profile.estate.location_source?.parcel_details && <p className="fi-help">Saved mapped outline: {(profile.estate.location_source.parcel_details.mapped_area_m2 / SQUARE_METRES_PER_ACRE).toLocaleString('en-IN', { maximumFractionDigits: 2 })} acres (approximate). This reference does not replace the confirmed total estate area below.</p>}{profile.estate.location_source?.rtc_reference && <p className="fi-help">Saved RTC extent: {rtcExtentText({ acres: profile.estate.location_source.rtc_reference.recorded_extent.acres, guntas: profile.estate.location_source.rtc_reference.recorded_extent.guntas, fractionalGuntas: profile.estate.location_source.rtc_reference.recorded_extent.fractional_guntas })} · Land code {profile.estate.location_source.rtc_reference.land_code}. Confirm your share before entering estate area.</p>}<p className="fi-help">State, district and taluk are required. Estate name, village and area can be added when known.</p><Fields value={profile.estate} onPatch={estate} fields={[{key:'estate_name',label:'Estate name',placeholder:'e.g. Green Valley Estate'},{key:'state',label:'State',required:true},{key:'district',label:'District',required:true},{key:'taluk',label:'Taluk',required:true},{key:'village',label:'Village',placeholder:'Your village'},{key:'total_area',label:'Total estate area',kind:'number'},{key:'area_unit',label:'Area unit',kind:'select',options:['acre','hectare']}]} /><details className="fi-optional-details"><summary>Optional location and land details</summary><Fields value={profile.estate} onPatch={estate} fields={[{key:'hobli',label:'Hobli'},{key:'gram_panchayat',label:'Gram panchayat'},{key:'pincode',label:'Pincode',maxLength:6},{key:'latitude',label:'Latitude (strongly encouraged)',kind:'number',min:-90,max:90},{key:'longitude',label:'Longitude (strongly encouraged)',kind:'number',min:-180,max:180},{key:'cultivated_area',label:'Cultivated area',kind:'number'},{key:'elevation_m',label:'Elevation (metres)',kind:'number',min:-500,max:9000}]} /><label className="fi-single-field"><span>Survey numbers (optional, separated by commas)</span><input value={surveyText} onChange={e=>{setSurveyText(e.target.value);estate({location_source:null})}} maxLength={1000} placeholder="e.g. 10/1, 10/2" /></label><p className="fi-help">Estate coordinates help find the nearest verified station when official observations become available. They never determine your insurance reference station.</p></details></>}
    {step===1&&<><p className="fi-help">Record physical land once. A block can contain coffee, pepper and arecanut together.</p>{profile.blocks.map((block,index)=><section className="fi-form-card" key={block.id??index}><div className="fi-card-heading"><h3>{block.name}</h3><button type="button" className="icon-button danger" aria-label={`Remove ${block.name}`} onClick={()=>setProfile(p=>({...p,blocks:p.blocks.filter((_,i)=>i!==index)}))}><Trash2 size={17}/></button></div><Fields value={block} onPatch={patch=>blockPatch(index,patch)} fields={[{key:'name',label:'Block name',maxLength:120,required:true,placeholder:'e.g. Upper block'},{key:'area',label:'Physical block area',kind:'number'},{key:'area_unit',label:'Area unit',kind:'select',options:['acre','hectare']},{key:'latitude',label:'Block latitude',kind:'number',min:-90,max:90},{key:'longitude',label:'Block longitude',kind:'number',min:-180,max:180},{key:'irrigation_type',label:'Irrigation type'},{key:'water_source',label:'Water source'},{key:'notes',label:'Farming notes',maxLength:2000}]} /></section>)}<button type="button" className="button-secondary" disabled={profile.blocks.length>=100} onClick={addBlock}><Plus size={17}/>Add a physical block</button></>}
    {step>=2&&step<=4&&cropsEditor(cropStep)}
    {step===5&&<><Checks label="Water sources" choices={water} value={profile.infrastructure.water_sources} onChange={values=>setProfile(p=>({...p,infrastructure:{...p.infrastructure,water_sources:values}}))}/><Checks label="Irrigation" choices={irrigation} value={profile.infrastructure.irrigation} onChange={values=>setProfile(p=>({...p,infrastructure:{...p.infrastructure,irrigation:values}}))}/><Fields value={profile.infrastructure} onPatch={patch=>setProfile(p=>({...p,infrastructure:{...p.infrastructure,...patch}}))} fields={[{key:'irrigated_area',label:'Irrigated area',kind:'number'},{key:'rainfed_area',label:'Rainfed area',kind:'number'},{key:'area_unit',label:'Area unit',kind:'select',options:['acre','hectare']},{key:'water_storage_capacity_l',label:'Water storage (litres)',kind:'number'},{key:'pump_hp',label:'Pump power (HP)',kind:'number'},{key:'summer_water_shortage',label:'Summer water shortage?',kind:'boolean'}]}/><h3 className="fi-subheading">Optional eligibility details</h3><Fields value={profile.farmer} onPatch={patch=>setProfile(p=>({...p,farmer:{...p.farmer,...patch}}))} fields={[{key:'farmer_type',label:'Farmer type',kind:'select',options:['individual','partnership','company','FPO','cooperative','other']},{key:'total_agricultural_landholding',label:'Total agricultural landholding',kind:'number'},{key:'area_unit',label:'Landholding unit',kind:'select',options:['acre','hectare']},{key:'coffee_board_grower_id_available',label:'Coffee Board grower registration available?',kind:'boolean'},{key:'fpo_member',label:'FPO member?',kind:'boolean'},{key:'cooperative_member',label:'Cooperative member?',kind:'boolean'},{key:'government_registration_status',label:'Registration status (no identity numbers)',maxLength:500}]} /></>}
    {step===6&&<><p className="fi-help">Record each crop independently. These details describe your policy; official coverage, station mapping and term sheets need separate verification. Keep policy identifiers in your secure document vault.</p>{profile.insurance.map((policy,index)=><section key={policy.crop} className="fi-form-card"><h3>{CROP_LABELS[policy.crop]}</h3><Fields value={policy} onPatch={patch=>setProfile(p=>({...p,insurance:p.insurance.map((value,i)=>i===index?{...value,...patch}:value)}))} fields={[{key:'currently_insured',label:'Currently insured?',kind:'boolean'},{key:'scheme_name',label:'Scheme name'},{key:'insurer',label:'Insurer'},{key:'policy_year',label:'Policy year (e.g. 2026–27)',maxLength:20},{key:'season',label:'Season',maxLength:80},{key:'sum_insured',label:'Sum insured (₹)',kind:'number'},{key:'premium_paid',label:'Premium paid (₹)',kind:'number'},{key:'weather_station_name',label:'Notified weather station name, if known'},{key:'weather_station_id',label:'Notified weather station ID, if known'}]} /></section>)}</>}
    {step===7&&<Checks label="Equipment and infrastructure present" choices={equipment} value={profile.infrastructure.equipment} onChange={values=>setProfile(p=>({...p,infrastructure:{...p.infrastructure,equipment:values}}))}/>}
    {step===8&&<><p className="fi-help">Choose updates to highlight in your in-app alert list. You can still browse other relevant updates in the feed.</p><div className="fi-preferences">{profile.preferences.map((preference,index)=><fieldset key={preference.kind}><legend>{nice(preference.kind)}</legend><label><input type="checkbox" checked={preference.enabled} onChange={e=>setProfile(p=>({...p,preferences:p.preferences.map((value,i)=>i===index?{...value,enabled:e.target.checked}:value)}))}/>Highlight these updates</label><div>{CROPS.map(crop=><label key={crop}><input type="checkbox" disabled={!preference.enabled} checked={preference.crops.includes(crop)} onChange={e=>setProfile(p=>({...p,preferences:p.preferences.map((value,i)=>i===index?{...value,crops:e.target.checked?[...value.crops,crop]:value.crops.filter(c=>c!==crop)}:value)}))}/>{CROP_LABELS[crop]}</label>)}</div></fieldset>)}</div></>}
    <Notice error>{error}</Notice><div className="fi-wizard-footer"><button type="button" className="button-secondary" disabled={step===0||saving} onClick={()=>move(step-1)}><ChevronLeft size={17}/>Back</button>{step<steps.length-1?<><button type="button" className="fi-skip" disabled={saving} onClick={()=>move(step+1)}>Skip for now</button><button type="button" className="button-primary" disabled={saving} onClick={()=>move(step+1)}>Next<ChevronRight size={17}/></button></>:<button type="submit" className="button-primary" disabled={saving}>{saving?'Saving…':'Save estate profile'}</button>}</div>
  </fieldset></form></Sheet>
}
