import { useMemo, useState, type FormEvent } from 'react'
import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { money } from '../lib/calculations'
import { supabase } from '../lib/supabase'
import type { CoffeePrice, EstateData } from '../lib/types'
import { ConfirmDialog } from './ConfirmDialog'

const empty = { price_date: new Date().toISOString().slice(0, 10), coffee_type: 'Arabica', grade: 'Standard', source: 'Manual entry', price_per_kg: '' }

export function Prices({ data, refresh }: { data: EstateData; refresh: () => Promise<void> }) {
  const [form, setForm] = useState(empty); const [editing, setEditing] = useState<CoffeePrice | null>(null); const [deleting, setDeleting] = useState<CoffeePrice | null>(null); const [message, setMessage] = useState('')
  const latest = data.prices[0]
  const priceHistory = useMemo(() => [...data.prices].filter((item) => Number(item.price_date.slice(0, 4)) >= new Date().getFullYear() - 5).sort((a, b) => a.price_date.localeCompare(b.price_date)).map((item) => ({ date: item.price_date, price: Number(item.price_per_kg) })), [data.prices])
  async function save(event: FormEvent) { event.preventDefault(); const payload = { ...form, price_per_kg: Number(form.price_per_kg) }; const result = editing ? await supabase.from('coffee_prices').update(payload).eq('id', editing.id) : await supabase.from('coffee_prices').insert(payload); setMessage(result.error ? result.error.message : editing ? 'Price updated.' : 'Price recorded.'); if (!result.error) { setForm(empty); setEditing(null); await refresh() } }
  async function remove() { if (!deleting) return; const { error } = await supabase.from('coffee_prices').delete().eq('id', deleting.id); setMessage(error ? error.message : 'Price deleted.'); setDeleting(null); if (!error) await refresh() }
  return <div className="page space-y-5"><header><p className="text-sm font-bold uppercase tracking-wider text-leaf-700">Market rates</p><h1 className="mt-1 text-3xl font-extrabold">Coffee prices</h1><p className="mt-1 text-stone-600">Record the rate you see each day. An external price importer can use the source and external ID fields later.</p></header>{message && <p className="rounded-xl bg-leaf-50 p-3 font-semibold text-leaf-700">{message}</p>}
    <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><form className="card space-y-3" onSubmit={save}><h2 className="text-xl font-extrabold">{editing ? 'Edit price' : 'Add daily price'}</h2><label className="label">Date<input className="field" type="date" value={form.price_date} onChange={(event) => setForm({ ...form, price_date: event.target.value })} required /></label><label className="label">Coffee type<input className="field" value={form.coffee_type} onChange={(event) => setForm({ ...form, coffee_type: event.target.value })} required /></label><label className="label">Grade<input className="field" value={form.grade} onChange={(event) => setForm({ ...form, grade: event.target.value })} required /></label><label className="label">Source<input className="field" value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })} required /></label><label className="label">Price per kg (₹)<input className="field" inputMode="decimal" value={form.price_per_kg} onChange={(event) => setForm({ ...form, price_per_kg: event.target.value })} required /></label><div className="flex flex-wrap gap-3"><button className="button-primary">{editing ? 'Save changes' : 'Save price'}</button>{editing && <button className="button-secondary" type="button" onClick={() => { setEditing(null); setForm(empty) }}>Cancel</button>}</div></form>
      <div className="card"><p className="text-sm font-bold uppercase tracking-wider text-stone-500">Latest recorded price</p><p className="mt-2 text-4xl font-extrabold text-leaf-700">{latest ? money(Number(latest.price_per_kg)) : '—'}<span className="text-base text-stone-500"> / kg</span></p>{latest && <p className="mt-2 text-stone-600">{latest.coffee_type} · {latest.grade} · {latest.price_date} · {latest.source}</p>}<div className="mt-5 h-65">{priceHistory.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={priceHistory}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="date" tick={{ fontSize: 11 }} /><YAxis tickFormatter={(item) => `₹${item}`} /><Tooltip formatter={(item) => money(Number(item))} /><Line dataKey="price" stroke="#3d6637" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer> : <div className="grid h-full place-items-center text-stone-500">Add prices to see five years of history.</div>}</div></div></section>
    <section className="card"><h2 className="text-xl font-extrabold">Price records</h2><div className="table-wrap mt-3"><table className="data-table"><thead><tr><th>Date</th><th>Type</th><th>Grade</th><th>Source</th><th>Rate / kg</th><th>Actions</th></tr></thead><tbody>{data.prices.map((item) => <tr key={item.id}><td>{item.price_date}</td><td>{item.coffee_type}</td><td>{item.grade}</td><td>{item.source}</td><td className="font-bold">{money(Number(item.price_per_kg))}</td><td><div className="flex gap-2"><button className="font-bold text-leaf-700 underline" onClick={() => { setEditing(item); setForm({ price_date: item.price_date, coffee_type: item.coffee_type, grade: item.grade, source: item.source, price_per_kg: String(item.price_per_kg) }) }}>Edit</button><button className="font-bold text-red-700 underline" onClick={() => setDeleting(item)}>Delete</button></div></td></tr>)}</tbody></table></div></section><ConfirmDialog open={!!deleting} title="Delete price record?" onCancel={() => setDeleting(null)} onConfirm={() => void remove()}>This market-price record will be permanently removed.</ConfirmDialog></div>
}
