import { useRef, useState, type FormEvent } from 'react'
import { money, productionMetrics } from '../lib/calculations'
import { scrollToEditor } from '../lib/scroll'
import { supabase } from '../lib/supabase'
import type { EstateData, ProductionRecord, Sale } from '../lib/types'
import { ConfirmDialog } from './ConfirmDialog'

const currentYear = new Date().getFullYear()
const productionBlank = { production_year: String(currentYear), bags_produced: '', bag_weight_kg: '50', notes: '' }
const saleBlank = { production_year: String(currentYear), sale_date: new Date().toISOString().slice(0, 10), bags_sold: '', selling_price_per_bag: '', buyer: '' }

export function Production({ data, year, refresh }: { data: EstateData; year: number; refresh: () => Promise<void> }) {
  const [production, setProduction] = useState(productionBlank); const [sale, setSale] = useState(saleBlank); const [editingProduction, setEditingProduction] = useState<ProductionRecord | null>(null); const [editingSale, setEditingSale] = useState<Sale | null>(null); const [removeProduction, setRemoveProduction] = useState<ProductionRecord | null>(null); const [removeSale, setRemoveSale] = useState<Sale | null>(null); const [message, setMessage] = useState('')
  const productionEditorRef = useRef<HTMLFormElement>(null)
  const saleEditorRef = useRef<HTMLFormElement>(null)
  const metrics = productionMetrics(data.production, data.sales, data.expenses, data.weeklyPayments, year)
  async function saveProduction(event: FormEvent) { event.preventDefault(); const payload = { production_year: Number(production.production_year), bags_produced: Number(production.bags_produced), bag_weight_kg: Number(production.bag_weight_kg), notes: production.notes || null }; const result = editingProduction ? await supabase.from('production_records').update(payload).eq('id', editingProduction.id) : await supabase.from('production_records').insert(payload); setMessage(result.error ? result.error.message : 'Production record saved.'); if (!result.error) { setProduction(productionBlank); setEditingProduction(null); await refresh() } }
  async function saveSale(event: FormEvent) { event.preventDefault(); const payload = { production_year: Number(sale.production_year), sale_date: sale.sale_date, bags_sold: Number(sale.bags_sold), selling_price_per_bag: Number(sale.selling_price_per_bag), buyer: sale.buyer }; const result = editingSale ? await supabase.from('sales').update(payload).eq('id', editingSale.id) : await supabase.from('sales').insert(payload); setMessage(result.error ? result.error.message : 'Sale saved.'); if (!result.error) { setSale(saleBlank); setEditingSale(null); await refresh() } }
  async function deleteRecord(table: 'production_records' | 'sales', id: string) { const { error } = await supabase.from(table).delete().eq('id', id); setMessage(error ? error.message : 'Record deleted.'); if (!error) await refresh() }
  function startProductionEdit(item: ProductionRecord) { setEditingProduction(item); setProduction({ production_year: String(item.production_year), bags_produced: String(item.bags_produced), bag_weight_kg: String(item.bag_weight_kg), notes: item.notes ?? '' }); scrollToEditor(productionEditorRef.current) }
  function startSaleEdit(item: Sale) { setEditingSale(item); setSale({ production_year: String(item.production_year), sale_date: item.sale_date, bags_sold: String(item.bags_sold), selling_price_per_bag: String(item.selling_price_per_bag), buyer: item.buyer }); scrollToEditor(saleEditorRef.current) }
  const cards = [['Bags produced', metrics.bagsProduced.toLocaleString(), 'production'], ['Bags sold', metrics.bagsSold.toLocaleString(), 'volume'], ['Revenue', money(metrics.revenue), 'revenue'], ['Total expenses', money(metrics.totalExpenses), 'expense'], ['Profit', money(metrics.profit), metrics.profit >= 0 ? 'profit' : 'loss'], ['Cost / bag', money(metrics.costPerBag), 'labour'], ['Profit / bag sold', money(metrics.profitPerBag), metrics.profitPerBag >= 0 ? 'profit' : 'loss']]
  return <div className="page space-y-5"><header><p className="text-sm font-bold uppercase tracking-wider text-leaf-700">Harvest & sales</p><h1 className="mt-1 text-3xl font-extrabold">Production and sales</h1><p className="mt-1 text-stone-600">Record harvest, each sale and the buyer. All business results are calculated automatically.</p></header>{message && <p className="rounded-xl bg-leaf-50 p-3 font-semibold text-leaf-700">{message}</p>}
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-4">{cards.map(([label, value, tone]) => <div className={`summary-tile tone-${tone}`} key={label}><p className="tile-label">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p></div>)}</section>
    <section className="grid gap-5 xl:grid-cols-2"><form ref={productionEditorRef} className="card scroll-mt-24 space-y-3" onSubmit={saveProduction}><h2 className="text-xl font-extrabold">{editingProduction ? 'Edit production' : 'Record production'}</h2><label className="label">Production year<input className="field" inputMode="numeric" value={production.production_year} onChange={(event) => setProduction({ ...production, production_year: event.target.value })} required /></label><label className="label">Bags produced<input className="field" inputMode="decimal" value={production.bags_produced} onChange={(event) => setProduction({ ...production, bags_produced: event.target.value })} required /></label><label className="label">Bag weight (kg)<input className="field" inputMode="decimal" value={production.bag_weight_kg} onChange={(event) => setProduction({ ...production, bag_weight_kg: event.target.value })} required /></label><label className="label">Notes (optional)<input className="field" value={production.notes} onChange={(event) => setProduction({ ...production, notes: event.target.value })} /></label><div className="flex flex-wrap gap-3"><button className="button-primary">Save production</button>{editingProduction && <button type="button" className="button-secondary" onClick={() => { setEditingProduction(null); setProduction(productionBlank) }}>Cancel</button>}</div></form>
      <form ref={saleEditorRef} className="card scroll-mt-24 space-y-3" onSubmit={saveSale}><h2 className="text-xl font-extrabold">{editingSale ? 'Edit sale' : 'Record sale'}</h2><label className="label">Sale date<input className="field" type="date" value={sale.sale_date} onChange={(event) => setSale({ ...sale, sale_date: event.target.value })} required /></label><label className="label">Production year<input className="field" inputMode="numeric" value={sale.production_year} onChange={(event) => setSale({ ...sale, production_year: event.target.value })} required /></label><label className="label">Number of bags sold<input className="field" inputMode="decimal" value={sale.bags_sold} onChange={(event) => setSale({ ...sale, bags_sold: event.target.value })} required /></label><label className="label">Selling price per bag (₹)<input className="field" inputMode="decimal" value={sale.selling_price_per_bag} onChange={(event) => setSale({ ...sale, selling_price_per_bag: event.target.value })} required /></label><label className="label">Buyer<input className="field" value={sale.buyer} onChange={(event) => setSale({ ...sale, buyer: event.target.value })} required /></label><div className="flex flex-wrap gap-3"><button className="button-primary">Save sale</button>{editingSale && <button type="button" className="button-secondary" onClick={() => { setEditingSale(null); setSale(saleBlank) }}>Cancel</button>}</div></form></section>
    <section className="card"><h2 className="text-xl font-extrabold">Production records</h2><div className="table-wrap mt-3"><table className="data-table"><thead><tr><th>Year</th><th>Bags</th><th>Bag weight</th><th>Notes</th><th>Actions</th></tr></thead><tbody>{data.production.map((item) => <tr key={item.id}><td>{item.production_year}</td><td>{item.bags_produced}</td><td>{item.bag_weight_kg} kg</td><td>{item.notes || '—'}</td><td><button className="font-bold text-leaf-700 underline" onClick={() => startProductionEdit(item)}>Edit</button><button className="ml-3 font-bold text-red-700 underline" onClick={() => setRemoveProduction(item)}>Delete</button></td></tr>)}</tbody></table></div></section>
    <section className="card"><h2 className="text-xl font-extrabold">Sales records</h2><div className="table-wrap mt-3"><table className="data-table"><thead><tr><th>Date</th><th>Buyer</th><th>Bags</th><th>Price / bag</th><th>Revenue</th><th>Actions</th></tr></thead><tbody>{data.sales.map((item) => <tr key={item.id}><td>{item.sale_date}</td><td>{item.buyer}</td><td>{item.bags_sold}</td><td>{money(Number(item.selling_price_per_bag))}</td><td className="font-bold">{money(Number(item.bags_sold) * Number(item.selling_price_per_bag))}</td><td><button className="font-bold text-leaf-700 underline" onClick={() => startSaleEdit(item)}>Edit</button><button className="ml-3 font-bold text-red-700 underline" onClick={() => setRemoveSale(item)}>Delete</button></td></tr>)}</tbody></table></div></section>
    <ConfirmDialog open={!!removeProduction} title="Delete production record?" onCancel={() => setRemoveProduction(null)} onConfirm={() => { if (removeProduction) void deleteRecord('production_records', removeProduction.id); setRemoveProduction(null) }}>This will permanently remove this harvest record.</ConfirmDialog>
    <ConfirmDialog open={!!removeSale} title="Delete sale record?" onCancel={() => setRemoveSale(null)} onConfirm={() => { if (removeSale) void deleteRecord('sales', removeSale.id); setRemoveSale(null) }}>This will permanently remove this sale and reduce reported revenue.</ConfirmDialog>
  </div>
}
